In [10]:
import camelot

In [11]:
import pandas as pd

In [12]:
tables = camelot.read_pdf("monthlyannualtemp.pdf", flavor="stream", pages="1-4")
tables

In [13]:
tables[2].df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,YEAR,JAN,,FEB MAR APR MAY,,,JUN,,JUL AUG,,SEP OCT NOV DEC ANNUAL,,,
1,1960,33.9,36.3,33.3,54.1,62.6,71.8,74.6,74.9,68.0,58.1,49.7,30.9,54.0
2,1961,27.7,36.7,41.5,49.0,59.9,72.3,78.1,76.4,73.6,61.1,48.8,35.5,55.1
3,1962,32.6,31.8,43.1,53.3,64.5,72.5,74.0,72.4,64.9,57.4,43.2,31.5,53.4
4,1963,30.1,28.3,43.7,53.7,61.1,70.9,76.4,72.1,63.1,61.8,50.4,31.2,53.6
5,1964,35.7,32.9,43.1,49.7,65.4,71.6,75.4,72.9,67.2,55.0,49.4,36.4,54.6
6,1965,29.7,33.9,40.0,50.6,66.4,70.1,74.3,73.2,67.5,57.3,46.8,40.5,54.2
7,1966,32.2,35.1,42.7,49.7,61.6,75.4,79.7,76.9,66.5,56.2,48.9,35.7,55.1
8,1967,37.4,29.2,37.6,49.6,55.2,72.8,75.3,73.9,66.7,57.2,42.5,38.2,53.0
9,1968,26.7,28.9,43.3,55.0,59.6,69.7,77.3,76.0,70.6,60.5,46.9,34.3,54.1
10,1969,31.8,32.6,40.1,55.9,65.3,73.1,74.8,77.4,69.0,57.7,46.4,33.4,54.8
11,1970,25.1,33.0,38.7,52.1,64.0,70.9,77.1,77.6,70.8,58.9,48.5,34.4,54.3
12,1971,27.0,35.1,40.1,50.8,61.4,74.2,77.8,75.9,71.6,62.7,45.1,40.8,55.2
13,1972,35.1,31.4,39.8,50.1,63.3,67.9,77.2,75.6,69.5,53.5,44.4,38.5,53.9
14,1973,35.5,32.5,46.4,53.4,59.5,73.4,77.4,77.6,69.5,60.2,48.3,39.0,56.1
15,1974,35.3,31.7,42.1,55.2,61.0,69.0,77.2,76.4,66.7,54.1,48.2,39.4,54.7
16,1975,37.3,35.8,40.2,47.9,65.8,70.5,75.8,74.4,64.2,59.2,52.3,35.9,54.9
17,1976,27.4,39.9,44.4,55.0,60.2,73.2,74.8,74.3,66.6,52.9,41.7,29.9,53.4
18,1977,22.1,33.5,46.8,53.7,65.0,70.2,79.0,75.7,68.2,54.9,47.3,35.7,54.3
19,1978,28.0,27.2,39.0,51.6,61.5,71.3,74.4,76.0,65.0,54.9,47.8,38.9,53.0
20,1979,33.6,25.5,46.9,52.6,65.3,69.2,76.9,76.8,70.5,57.3,52.5,41.1,55.7
21,1980,33.7,31.4,41.2,54.5,65.6,70.3,79.3,80.3,70.8,55.2,44.6,32.5,55.0
22,1981,26.3,39.3,42.3,56.2,64.8,73.0,78.5,76.0,67.6,54.4,47.7,36.5,55.2
23,1982,26.1,35.3,42.0,51.2,64.1,68.6,77.9,73.2,68.3,58.5,50.4,42.8,54.9
24,1983,34.5,36.4,44.0,52.3,60.2,73.4,79.5,77.7,71.8,57.9,48.9,35.2,56.0
25,1984,29.9,40.6,36.7,51.9,61.6,74.5,74.7,76.7,65.9,61.8,47.3,43.8,55.5
26,1985,28.8,36.6,45.8,55.5,65.3,68.6,76.2,75.4,70.5,59.5,50.0,34.2,55.5
27,1986,34.1,32.0,45.1,54.5,66.0,71.6,76.0,73.1,67.9,58.0,45.7,39.0,55.3
28,1987,32.3,33.2,45.2,53.4,63.6,72.8,78.0,74.2,67.9,53.8,47.7,39.5,55.1
29,1988,29.5,35.0,43.6,51.2,62.7,71.8,79.3,78.8,67.4,52.8,49.4,35.9,54.8
30,1989,37.4,34.5,42.4,52.2,62.1,72.0,75.0,74.0,68.1,58.2,45.7,25.9,54.0
31,1990,41.4,39.8,45.1,53.5,60.2,72.1,76.8,75.3,67.5,61.9,50.4,42.6,57.2
32,1991,34.9,40.0,44.6,55.7,68.7,74.1,77.7,77.1,67.5,58.4,48.3,39.6,57.2
33,1992,35.7,36.4,40.0,50.5,61.0,70.3,74.2,73.0,67.2,54.5,46.5,37.9,53.9
34,1993,36.3,30.8,39.7,53.3,65.7,73.3,80.2,77.2,67.3,56.0,48.8,37.3,55.5
35,1994,25.6,30.6,40.7,55.6,61.8,75.2,79.4,74.0,67.6,58.0,52.0,42.2,55.2
36,1995,37.5,31.6,45.0,51.9,61.9,71.8,79.2,78.6,68.3,61.6,43.6,32.4,55.3
37,1996,30.5,33.9,38.9,52.2,61.1,71.4,73.4,74.5,68.0,56.4,43.0,41.3,53.7
38,1997,32.2,40.0,41.9,51.7,59.4,70.9,75.8,73.3,67.0,56.8,44.5,38.3,54.3
39,1998,40.0,40.6,45.4,54.0,64.3,69.2,76.5,76.7,70.2,57.6,48.1,43.2,57.2
40,1999,33.9,38.9,42.5,53.5,63.1,73.2,81.4,75.5,69.1,56.0,50.6,40.0,56.5
41,2000,31.3,37.3,47.2,51.0,63.5,71.3,72.3,72.7,66.0,57.0,45.3,31.1,53.9
42,2001,33.6,35.9,39.6,54.2,63.8,72.9,73.2,78.7,67.7,58.5,52.7,44.1,56.3
43,2002,39.9,40.6,44.1,56.1,60.7,71.4,78.8,77.7,70.2,55.2,46.0,36.0,56.4
44,2003,27.5,30.1,43.1,49.8,58.7,68.3,75.8,76.7,67.9,55.1,50.0,37.6,53.4
45,2004,24.7,35.0,43.5,53.6,65.2,71.2,74.5,74.2,69.3,56.0,48.2,38.4,54.5
46,2005,31.3,36.5,39.4,55.1,58.9,74.0,77.5,79.7,73.3,57.9,49.6,35.3,55.8
47,2006,40.9,35.7,43.1,55.7,63.1,71.0,77.9,75.8,66.6,56.2,51.9,43.6,56.8
48,2007,37.5,28.2,42.2,50.3,65.2,71.4,75.0,74.0,70.3,63.6,45.4,37.0,55.0

In [16]:
df = pd.concat([
    tables[0].df,
    tables[1].df,
    tables[2].df,
    tables[3].df,
], ignore_index=True)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,,,,Average Monthly & Annual Temperatures at Centr...,,,,,,,,,,
1,,,,,,,Last Updated: 5/9/21,,,,,,,
2,YEAR,JAN,,FEB MAR APR MAY,,,JUN,,JUL AUG,,SEP OCT NOV DEC ANNUAL,,,
3,1869,35.1,34.5,34.8,49.2,57.7,69.3,72.8,71.8,65.6,50.9,40.3,34.7,51.4
4,1870,37.5,31.3,34.1,50.7,60.9,72.9,76.6,75.3,67.6,56.7,45.5,34.1,53.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2017,38.0,41.6,39.2,57.2,61.1,72.0,76.8,74.0,70.5,64.1,46.6,33.4,56.3
155,2018,31.7,42.0,40.1,49.5,66.9,71.7,77.6,78.1,70.7,57.7,44.4,40.1,55.9
156,2019,32.5,36.2,41.7,55.5,62.2,71.7,79.6,75.5,70.4,59.9,43.9,38.3,55.6
157,2020,39.1,40.1,48.0,50.4,60.3,73.7,80.0,76.9,68.8,57.9,53.0,39.2,57.3
158,2021,34.8,34.2,45.8,54.6,,,,,,,,,

In [17]:
#Change the columns
df = df.rename(columns={
    0: 'YEAR',
    1: 'JAN',
    2: 'FEB',
    3: 'MAR',
    4: 'APR',
    5: 'MAY',
    6: 'JUN',
    7: 'JUL',
    8: 'AUG',
    9: 'SEP',
    10: 'OCT',
    11: 'NOV',
    12: 'DEC',
    13: 'ANNUAL'
})
df = df[df['YEAR'] != 'YEAR']
df

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL
0,,,,Average Monthly & Annual Temperatures at Centr...,,,,,,,,,,
1,,,,,,,Last Updated: 5/9/21,,,,,,,
3,1869,35.1,34.5,34.8,49.2,57.7,69.3,72.8,71.8,65.6,50.9,40.3,34.7,51.4
4,1870,37.5,31.3,34.1,50.7,60.9,72.9,76.6,75.3,67.6,56.7,45.5,34.1,53.6
5,1871,28.3,30.2,44.2,52.0,60.4,68.2,72.3,73.6,60.8,55.6,38.8,29.2,51.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2017,38.0,41.6,39.2,57.2,61.1,72.0,76.8,74.0,70.5,64.1,46.6,33.4,56.3
155,2018,31.7,42.0,40.1,49.5,66.9,71.7,77.6,78.1,70.7,57.7,44.4,40.1,55.9
156,2019,32.5,36.2,41.7,55.5,62.2,71.7,79.6,75.5,70.4,59.9,43.9,38.3,55.6
157,2020,39.1,40.1,48.0,50.4,60.3,73.7,80.0,76.9,68.8,57.9,53.0,39.2,57.3
158,2021,34.8,34.2,45.8,54.6,,,,,,,,,

In [18]:
#drop any rows that have unnecessary values in the rebounds columns
df = df[df.MAR != "Average Monthly & Annual Temperatures at Central Park"]

In [19]:
df = df[df.JUN != "Last Updated: 5/9/21"]

In [20]:
df

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL
3,1869,35.1,34.5,34.8,49.2,57.7,69.3,72.8,71.8,65.6,50.9,40.3,34.7,51.4
4,1870,37.5,31.3,34.1,50.7,60.9,72.9,76.6,75.3,67.6,56.7,45.5,34.1,53.6
5,1871,28.3,30.2,44.2,52.0,60.4,68.2,72.3,73.6,60.8,55.6,38.8,29.2,51.1
6,1872,28.8,29.9,30.5,49.4,61.5,71.2,77.5,75.6,66.4,53.2,41.0,26.7,51.0
7,1873,28.6,29.5,35.7,46.7,58.8,70.3,75.4,72.0,65.4,55.8,37.0,36.5,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2017,38.0,41.6,39.2,57.2,61.1,72.0,76.8,74.0,70.5,64.1,46.6,33.4,56.3
155,2018,31.7,42.0,40.1,49.5,66.9,71.7,77.6,78.1,70.7,57.7,44.4,40.1,55.9
156,2019,32.5,36.2,41.7,55.5,62.2,71.7,79.6,75.5,70.4,59.9,43.9,38.3,55.6
157,2020,39.1,40.1,48.0,50.4,60.3,73.7,80.0,76.9,68.8,57.9,53.0,39.2,57.3
158,2021,34.8,34.2,45.8,54.6,,,,,,,,,

In [21]:
df.to_csv('Central_Park.csv', index=False)